# Use the latest version of Ubuntu as the base image
FROM ubuntu:latest

# Update the system and install required packages
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y nginx openssl

# Copy the Nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Copy the SSL certificate and key
COPY server.crt /etc/ssl/certs/server.crt
COPY server.key /etc/ssl/private/server.key

# Set the default command to start Nginx
CMD ["nginx", "-g", "daemon off;"]
