---
- name: Configure and deploy ifconfig service
  hosts: all
  become: true

  vars:
    maxmind_db_url: https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key={{ maxmind_license_key }}&suffix=tar.gz
    maxmind_db_archive: GeoLite2-City.tar.gz
    maxmind_db_dir: GeoLite2-City

  tasks:
    # Update and secure OS
    - name: Update and secure Debian OS
      apt:
        update_cache: yes
        upgrade: dist
        state: latest
      register: apt_output
      changed_when: apt_output.stdout_lines | length > 0

    # Install web server
    - name: Install nginx
      apt:
        name: nginx
        state: latest

    # Configure nginx
    - name: Configure nginx
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx

    # Create SSL certificate
    - name: Create self-signed SSL certificate
      command: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/cert.key -out /etc/nginx/cert.crt -subj "/C=LT/ST=Vilnius/L=Vilnius/O=MyCompany/OU=IT Department/CN=localhost"

    # Download MaxMind GeoLite2-City database
    - name: Download MaxMind GeoLite2-City database
      get_url:
        url: "{{ maxmind_db_url }}"
        dest: "{{ maxmind_db_archive }}"
      register: download_output

    # Extract MaxMind GeoLite2-City database
    - name: Extract MaxMind GeoLite2-City database
      unarchive:
        src: "{{ maxmind_db_archive }}"
        dest: /usr/share/GeoIP/
        copy: no
        creates: /usr/share/GeoIP/{{ maxmind_db_dir }}

    # Install required Python modules
    - name: Install required Python modules
      pip:
        name: geoip2
        state: latest

    # Copy Python script to server
    - name: Copy ifconfig script to server
      copy:
        src: ifconfig.py
        dest: /usr/local/bin/ifconfig.py
        mode: '0755'

    # Start nginx service
    - name: Start nginx service
      systemd:
        name: nginx
        state: started

  handlers:
    # Restart nginx service
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
